[project]
name = "xvr"
version = "0.0.0rc1"
description = "Differentiable 2D/3D X-ray to volume registration"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name = "Vivek Gopalakrishnan", email = "vivekg@mit.edu" }
]
requires-python = ">=3.10"
dependencies = [
    "antspyx>=0.5.4",
    "click>=8.1.8",
    "diffdrr>=0.5.0",
    "pydicom[pixeldata]>=3.0.1",
    "wandb>=0.19.8",
]

[project.scripts]
xvr = "xvr.cli:cli"

[project.urls]
Repository = "https://github.com/eigenvivek/xvr"
Issues = "https://github.com/eigenvivek/xvr/issues"

[tool.ruff]
extend-exclude = ["*.ipynb"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "diffdrrdata>=0.0.7",
    "huggingface-hub>=0.29.3",
]
